### ISSUE TITLE
HTML Validation Error

### ISSUE THREAD

**Issue by sagehartly** [sagehartly/dsn1674-project-3#1]
@thomasjbradley

I am just doing my final validations on my code and I get an error that I don't recognize. It says there is something wrong with my fonts code line in the head of my html. Everything looks fine though so should I ignore it?

I've attached a screen cap of my code as well as a screen cap of the error notification.

Thank you!
- Sage Mosurinjohn

![screen shot 2015-04-18 at 11 50 21 am](https://cloud.githubusercontent.com/assets/10467637/7216120/8d4c91d4-e5c1-11e4-9fce-a4daaaceb4cd.png)
![screen shot 2015-04-18 at 11 50 09 am](https://cloud.githubusercontent.com/assets/10467637/7216121/8e8a3ae2-e5c1-11e4-8917-a4d0dd3eca74.png)

**Comment by thomasjbradley** [comment]
Don't worry about that error; there's nothing we can do to fix it.

**Comment by sagehartly** [comment]
Great - thank you!
